name = "smartfit-academy"
compatibility_date = "2025-01-01"
main = "worker/index.ts"
minify = true

assets = { directory = "dist" }

# [build]
# command = "npm run build:prod"
# watch_dir = "src"

# Custom domain configuration
routes = [
	{ pattern = "smartfit.academy", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "progressive-ai-academy-db"
database_id = "41e55b1a-a336-4a6d-b833-b3508791c9f3"
