import { motion } from 'motion/react';
import { Link } from 'react-router-dom';

const fadeInUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, ease: 'easeOut' },
};

const sections = [
  {
    id: '1',
    heading: '1. Who We Are',
    body: (
      <p>
        Good Feed ("we," "our," or "us") operates the educational content platform at{' '}
        <a href="https://good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
          good-feed.com
        </a>
        . We are based in Austin, Texas, USA.
      </p>
    ),
  },
  {
    id: '2',
    heading: '2. Who Can Use Good Feed',
    body: (
      <>
        <p>
          You must be at least 13 years old to use Good Feed. By using the platform, you confirm
          that you are 13 or older.
        </p>
        <p className="mt-4">
          If you are between 13 and 17, you represent that your parent or legal guardian has reviewed and
          agrees to these Terms on your behalf. If you are using the platform on behalf of an educational
          institution or other organisation, you represent that you have the authority to bind that
          organisation to these Terms.
        </p>
      </>
    ),
  },
  {
    id: '3',
    heading: '3. Your Account',
    body: (
      <>
        <p>
          To access certain features you must create an account. Account creation and authentication are
          managed through{' '}
          <a href="https://clerk.com" className="text-primary underline underline-offset-2 hover:opacity-80">
            Clerk
          </a>
          .
        </p>
        <p className="mt-4">You are responsible for:</p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-foreground/80">
          <li>Providing accurate, current, and complete information when registering</li>
          <li>Keeping your login credentials confidential — do not share your password with anyone</li>
          <li>All activity that occurs under your account, whether or not authorised by you</li>
          <li>
            Notifying us promptly at{' '}
            <a href="mailto:support@good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
              support@good-feed.com
            </a>{' '}
            if you believe your account has been compromised
          </li>
        </ul>
        <p className="mt-4">
          We reserve the right to suspend or terminate accounts that violate these Terms, are inactive for
          an extended period, or where we have reason to believe they were created fraudulently.
        </p>
      </>
    ),
  },
  {
    id: '4',
    heading: '4. The Platform and Its Content',
    body: (
      <>
        <p>
          Good Feed provides an educational content platform that connects users with lessons,
          tools, and AI-generated content designed to deepen knowledge and curiosity — including features
          that link current cultural topics to classical texts and historical ideas.
        </p>
        <p className="mt-4">
          The platform is under active development. Content, features, and the overall product experience
          will change over time. Some features are marked as experimental or "coming soon." We do not
          guarantee that any specific feature will remain available.
        </p>
        <p className="mt-4">
          <strong>AI-generated content.</strong> Some content — including responses from the Modern
          Relevance tool and the Dashboard topic explorer — is generated by AI. While we work to ensure
          quality and accuracy, AI-generated content may be incomplete, incorrect, or not suited to all
          contexts. It is provided for educational exploration, not as authoritative academic or
          professional advice.
        </p>
      </>
    ),
  },
  {
    id: '5',
    heading: '5. Subscription Plans and Payment',
    body: (
      <>
        <p className="font-semibold text-foreground">Plans</p>
        <p className="mt-2">Good Feed offers the following plans:</p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-foreground/80">
          <li>
            <strong>Free Forever</strong> — available to all registered users at no cost; access to a
            defined subset of content and features
          </li>
          <li>
            <strong>Monthly Subscription ($7.99/month)</strong> — full platform access as described on
            the{' '}
            <Link to="/pricing" className="text-primary underline underline-offset-2 hover:opacity-80">
              Pricing page
            </Link>{' '}
            at the time of purchase
          </li>
          <li>
            <strong>Enterprise</strong> — custom pricing for institutional or organisational use; contact
            us at{' '}
            <a href="mailto:support@good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
              support@good-feed.com
            </a>
          </li>
        </ul>

        <p className="mt-6 font-semibold text-foreground">Billing</p>
        <p className="mt-2">
          Subscriptions are billed through Stripe, managed via Clerk's pricing table. By subscribing, you
          authorise Good Feed to charge your payment method on a recurring monthly (or annual, if
          selected) basis until you cancel. All prices are in US Dollars. We do not store your payment
          card details — these are handled exclusively by Stripe.
        </p>

        <p className="mt-6 font-semibold text-foreground">Cancellation</p>
        <p className="mt-2">
          You may cancel your subscription at any time through your account settings. Cancellation takes
          effect at the end of your current billing period. You will retain full access to your paid plan
          until that date. After the period ends, your account reverts to the Free Forever tier.
        </p>

        <p className="mt-6 font-semibold text-foreground">No Refunds</p>
        <p className="mt-2">
          All subscription fees are non-refundable. We do not provide partial refunds for unused time
          within a billing period. If you cancel mid-period, you will not receive a refund for the
          remaining days, but you will retain access until the period ends. Exceptions may apply where
          required by applicable consumer protection law.
        </p>

        <p className="mt-6 font-semibold text-foreground">Price Changes</p>
        <p className="mt-2">
          We reserve the right to change subscription pricing. We will provide at least 30 days' advance
          notice of any price change by email or through a notice on the platform. Your continued use of
          a paid subscription after a price change takes effect constitutes your acceptance of the new
          price. If you do not accept a price change, you may cancel your subscription before it takes
          effect.
        </p>
      </>
    ),
  },
  {
    id: '6',
    heading: '6. Acceptable Use',
    body: (
      <>
        <p>
          You agree to use Good Feed only for lawful purposes and in accordance with these Terms.
          You agree not to:
        </p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-foreground/80">
          <li>Use the platform for any purpose that violates applicable law or regulation</li>
          <li>
            Attempt to gain unauthorised access to any part of the platform, its systems, or other users'
            accounts
          </li>
          <li>
            Scrape, crawl, or systematically copy platform content in bulk without our written permission
          </li>
          <li>Use automated tools to access, interact with, or extract data from the platform</li>
          <li>
            Impersonate any person or entity, or misrepresent your affiliation with any person or entity
          </li>
          <li>
            Upload, transmit, or distribute any content that is harmful, abusive, threatening, or unlawful
          </li>
          <li>
            Reverse engineer, decompile, or attempt to extract the source code of any part of the platform
          </li>
          <li>
            Resell, sublicence, or commercially exploit platform content or access without our written
            consent
          </li>
          <li>Use the platform to develop a competing product or service</li>
          <li>Interfere with or disrupt the platform's infrastructure or the experience of other users</li>
        </ul>
        <p className="mt-4">
          We reserve the right to suspend or permanently terminate access for violations of this section
          without notice.
        </p>
      </>
    ),
  },
  {
    id: '7',
    heading: '7. Intellectual Property',
    body: (
      <>
        <p>
          <strong>Our content.</strong> All content on Good Feed — including lesson text, generated
          educational content, tool outputs, design, graphics, software, and the Good Feed name and
          logo — is owned by Good Feed or licensed to us. Your subscription grants you a personal,
          non-exclusive, non-transferable licence to access and use this content for your own private
          educational purposes only.
        </p>
        <p className="mt-4">
          You may not copy, reproduce, distribute, publicly display, modify, create derivative works from,
          or otherwise exploit platform content for any commercial purpose, or share it at scale, without
          our prior written permission.
        </p>
        <p className="mt-4">
          <strong>Third-party works.</strong> Good Feed references and discusses third-party works
          — including books, films, and other cultural works — for educational and commentary purposes.
          All third-party trademarks, titles, and characters remain the property of their respective
          owners. Our use of such references does not imply any affiliation with or endorsement by those
          owners.
        </p>
        <p className="mt-4">
          <strong>Feedback.</strong> If you submit feedback, suggestions, or ideas about the platform to
          us, you grant us a perpetual, irrevocable, royalty-free licence to use that feedback for any
          purpose, without obligation to compensate you.
        </p>
      </>
    ),
  },
  {
    id: '8',
    heading: '8. Third-Party Services',
    body: (
      <p>
        The platform integrates with third-party services including Clerk (authentication), Stripe
        (payments), and PostHog (analytics). Your use of these services is subject to their respective
        terms and privacy policies. We are not responsible for the practices or content of third-party
        services.
      </p>
    ),
  },
  {
    id: '9',
    heading: '9. Disclaimer of Warranties',
    body: (
      <>
        <p>
          Good Feed is provided "as is" and "as available" without warranties of any kind, express
          or implied. To the fullest extent permitted by law, we disclaim all warranties including implied
          warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </p>
        <p className="mt-4">We do not warrant that:</p>
        <ul className="mt-3 space-y-2 list-disc list-inside text-foreground/80">
          <li>
            The platform will be uninterrupted, error-free, or free of viruses or harmful components
          </li>
          <li>
            AI-generated content will be accurate, complete, or appropriate for any specific purpose
          </li>
          <li>
            The platform will meet your particular educational needs or produce any specific learning
            outcome
          </li>
          <li>Any errors will be corrected</li>
        </ul>
      </>
    ),
  },
  {
    id: '10',
    heading: '10. Limitation of Liability',
    body: (
      <>
        <p>
          To the maximum extent permitted by applicable law, Good Feed and its team members shall
          not be liable for any indirect, incidental, consequential, special, or punitive damages arising
          out of or related to your use of (or inability to use) the platform — including loss of data,
          loss of revenue, or loss of goodwill — even if we have been advised of the possibility of such
          damages.
        </p>
        <p className="mt-4">
          Our total cumulative liability to you for any claim arising out of or related to these Terms or
          the platform shall not exceed the greater of (a) the total amount you paid us in the 12 months
          immediately preceding the claim, or (b) $50 USD.
        </p>
        <p className="mt-4">
          Some jurisdictions do not allow the exclusion or limitation of certain damages, so some of the
          above may not apply to you.
        </p>
      </>
    ),
  },
  {
    id: '11',
    heading: '11. Indemnification',
    body: (
      <p>
        You agree to defend, indemnify, and hold harmless Good Feed and its team members from any
        claims, damages, losses, and costs (including reasonable legal fees) arising from your use of the
        platform, your violation of these Terms, or your violation of any third party's rights.
      </p>
    ),
  },
  {
    id: '12',
    heading: '12. Governing Law and Disputes',
    body: (
      <>
        <p>
          These Terms are governed by and construed in accordance with the laws of the State of Texas,
          USA, without regard to its conflict of law provisions.
        </p>
        <p className="mt-4">
          Any dispute arising out of or relating to these Terms or the platform shall be submitted to the
          exclusive jurisdiction of the state and federal courts located in Austin, Texas. You consent to
          personal jurisdiction in those courts.
        </p>
        <p className="mt-4">
          Before initiating any formal legal proceeding, we encourage you to contact us at{' '}
          <a href="mailto:support@good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
            support@good-feed.com
          </a>{' '}
          to attempt an informal resolution. Many issues can be resolved quickly and without litigation.
        </p>
      </>
    ),
  },
  {
    id: '13',
    heading: '13. Changes to These Terms',
    body: (
      <>
        <p>
          We may update these Terms from time to time. If we make material changes, we will notify you by
          email or by posting a notice on the platform at least 14 days before the changes take effect.
        </p>
        <p className="mt-4">
          Your continued use of Good Feed after updated Terms take effect constitutes your
          acceptance of the new Terms. If you do not agree to the updated Terms, you must stop using the
          platform and may cancel your subscription.
        </p>
      </>
    ),
  },
  {
    id: '14',
    heading: '14. Termination',
    body: (
      <>
        <p>
          We may suspend or terminate your access to the platform at any time, with or without notice, if
          we believe you have violated these Terms, if required by law, or for any other operational
          reason. Upon termination, your licence to use the platform ends immediately.
        </p>
        <p className="mt-4">
          If we terminate your account without cause, we will provide a pro-rata refund of any prepaid
          subscription fees for the unused portion of your current billing period.
        </p>
        <p className="mt-4">
          You may terminate your account at any time by cancelling your subscription and deleting your
          account through account settings, or by contacting{' '}
          <a href="mailto:support@good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
            support@good-feed.com
          </a>
          .
        </p>
      </>
    ),
  },
  {
    id: '15',
    heading: '15. Entire Agreement',
    body: (
      <>
        <p>
          These Terms, together with our Privacy Policy, constitute the entire agreement between you and
          Good Feed regarding your use of the platform. They supersede any prior agreements or
          understandings, whether written or oral.
        </p>
        <p className="mt-4">
          If any provision of these Terms is found to be unenforceable, that provision will be modified to
          the minimum extent necessary to make it enforceable, and the remaining provisions will remain in
          full effect.
        </p>
        <p className="mt-4">
          Our failure to enforce any provision of these Terms does not constitute a waiver of our right to
          enforce it in the future.
        </p>
      </>
    ),
  },
  {
    id: '16',
    heading: '16. Contact',
    body: (
      <>
        <p>For questions about these Terms or to resolve a concern, contact us at:</p>
        <address className="mt-4 not-italic space-y-1 text-foreground/80">
          <p className="font-semibold text-foreground">Good Feed</p>
          <p>Austin, Texas, USA</p>
          <p>
            Email:{' '}
            <a href="mailto:support@good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
              support@good-feed.com
            </a>
          </p>
          <p>
            Website:{' '}
            <a href="https://good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
              https://good-feed.com
            </a>
          </p>
        </address>
      </>
    ),
  },
];

export default function Terms() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--color-palette-3)' }}>
      {/* Hero */}
      <section className="border-b" style={{ borderColor: 'var(--color-palette-4)' }}>
        <div className="content-container-sm mx-auto px-6 py-16 md:py-24">
          <motion.div {...fadeInUp}>
            <p className="text-sm font-medium uppercase tracking-widest mb-4" style={{ color: 'var(--color-palette-5)' }}>
              Legal
            </p>
            <h1 className="text-4xl md:text-5xl font-light leading-tight mb-4" style={{ fontFamily: 'Brockmann, sans-serif' }}>
              Terms of Service
            </h1>
            <p className="text-base text-foreground/60">Last updated: March 2026</p>
          </motion.div>
        </div>
      </section>

      {/* Intro */}
      <section className="content-container-sm mx-auto px-6 pt-12 pb-4">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: 'easeOut', delay: 0.1 }}
          className="prose prose-neutral max-w-none text-foreground/80 leading-relaxed space-y-4"
        >
          <p>
            Welcome to Good Feed. By accessing or using our platform at{' '}
            <a href="https://good-feed.com" className="text-primary underline underline-offset-2 hover:opacity-80">
              good-feed.com
            </a>
            , you agree to be bound by these Terms of Service ("Terms"). Please read them carefully
            before using the platform.
          </p>
          <p className="font-medium text-foreground">
            If you do not agree to these Terms, do not create an account or use the platform.
          </p>
        </motion.div>
      </section>

      {/* Sections */}
      <section className="content-container-sm mx-auto px-6 pt-8 pb-24 space-y-10">
        {sections.map((section, i) => (
          <motion.div
            key={section.id}
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.5, ease: 'easeOut', delay: i < 3 ? i * 0.05 : 0 }}
            id={`section-${section.id}`}
            className="scroll-mt-24"
          >
            <div
              className="rounded-2xl p-8 border"
              style={{
                background: 'rgba(255,255,255,0.55)',
                borderColor: 'var(--color-palette-4)',
                backdropFilter: 'blur(4px)',
              }}
            >
              <h2
                className="text-xl font-semibold mb-4"
                style={{ fontFamily: 'Brockmann, sans-serif', color: 'var(--color-palette-5)' }}
              >
                {section.heading}
              </h2>
              <div className="text-foreground/80 leading-relaxed text-[0.95rem]">{section.body}</div>
            </div>
          </motion.div>
        ))}
      </section>
    </div>
  );
}
